---
apiVersion: v1
kind: Service
metadata:
  name: order-processor
  namespace: eshop
  labels:
    app: order-processor
spec:
  selector:
    app: order-processor
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: order-processor
          image: sarialbebeto/order-processor:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__OrderingDb
              value: "Host=postgres;Port=5432;Database=orderingdb;Username=postgres;Password=postgres;"
            - name: RabbitMQ__Host
              value: "eventbus"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
