---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor
  namespace: eshop
  labels:
    app: payment-processor
spec:
  selector:
    app: payment-processor
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
  namespace: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
        - name: payment-processor
          image: sarialbebeto/payment-processor:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: RabbitMQ__Host
              value: "eventbus"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
